spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://47.106.129.11/demo?characterEncoding=utf-8&useSSL=true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  devtools:
    restart:
      enabled: true
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8
server:
  tomcat:
    uri-encoding: UTF-8
  port: 8080

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
  page-size-zero: false